// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddAuthProfile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<string>;

export function AddRepo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function CancelClone():Promise<void>;

export function DeleteAuthProfile(arg1:string):Promise<string>;

export function DeleteRepo(arg1:string):Promise<string>;

export function ExportCSVTemplate():Promise<string>;

export function GetAuthProfiles():Promise<Array<domain.AuthProfile>>;

export function GetConfig():Promise<domain.WorkspaceConfig>;

export function GetRepos():Promise<Array<domain.Repo>>;

export function ImportCSV():Promise<string>;

export function SaveConfig(arg1:string,arg2:number):Promise<string>;

export function SendFailureResponse(arg1:string):Promise<void>;

export function StartClone(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function SyncProvider(arg1:string):Promise<string>;

export function UpdateRepo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;
