// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAuthProfile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddAuthProfile'](arg1, arg2, arg3, arg4, arg5);
}

export function AddRepo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddRepo'](arg1, arg2, arg3, arg4);
}

export function CancelClone() {
  return window['go']['main']['App']['CancelClone']();
}

export function DeleteAuthProfile(arg1) {
  return window['go']['main']['App']['DeleteAuthProfile'](arg1);
}

export function DeleteRepo(arg1) {
  return window['go']['main']['App']['DeleteRepo'](arg1);
}

export function ExportCSVTemplate() {
  return window['go']['main']['App']['ExportCSVTemplate']();
}

export function GetAuthProfiles() {
  return window['go']['main']['App']['GetAuthProfiles']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRepos() {
  return window['go']['main']['App']['GetRepos']();
}

export function ImportCSV() {
  return window['go']['main']['App']['ImportCSV']();
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function SendFailureResponse(arg1) {
  return window['go']['main']['App']['SendFailureResponse'](arg1);
}

export function StartClone(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartClone'](arg1, arg2, arg3);
}

export function SyncProvider(arg1) {
  return window['go']['main']['App']['SyncProvider'](arg1);
}

export function UpdateRepo(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateRepo'](arg1, arg2, arg3, arg4, arg5);
}
